version: 2
updates:

  # originGUI
  - package-ecosystem: "npm"
    directory: "/originGUI"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[originGUI]"
    assignees:
      - "alexey-max-fedorov"

  # extension
  - package-ecosystem: "npm"
    directory: "/extension"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[extension]"
    assignees:
      - "alexey-max-fedorov"

  # typings
  - package-ecosystem: "npm"
    directory: "/typings"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[typings]"
    assignees:
      - "alexey-max-fedorov"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[Actions]"
    assignees:
      - "alexey-max-fedorov"
